#define FEATURE_VRAM_RGBA
// #define CONFIG_HELLO_WORLD

#define FEATURE_SHOW_FREE_MEMORY

#undef CONFIG_CRASH_LOG
#undef CONFIG_ADDITIONAL_VERSION
#undef CONFIG_TSKMON
#undef CONFIG_PROP_REQUEST_CHANGE
#undef CONFIG_AUTOBACKUP_ROM

